apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: https
      nodePort: 32351
      port: 443
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
