apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 32000
      port: 9090
      protocol: TCP
      targetPort: 3000
    - name: https
      nodePort: 32002
      port: 443
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
